In [2]:
import numpy as np
a = np.array([2,3,4])
b = np.array([2.0,2.5,4.4])

print("The data type of a is:", a.dtype) #datatype of a is int
print("The data type of b is:", b.dtype) #datatype of a is float

The data type of a is: int64
The data type of b is: float64


In [7]:
arr2D = np.array([[1,2,3,4],[4,5,6,8]])
print (arr2D)

comparr = np.array([[1,2],[3,4]],dtype=complex) #complex @D array
print("\n",comparr)

[[1 2 3 4]
 [4 5 6 8]]

 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [19]:
#array full of zero and ones and random no.s
array0 = np.zeros(3)
array2D0 = np.zeros((2,3))
print(array0, '\n',array2D0)

array1 = np.ones(4)
array2D1 = np.ones((4,5))
print('\n',array1, '\n',array2D1)

rndarray = np.random.random((3,2))
print('\n',rndarray)

#creating empty array:
emparray = np.empty((2,3))
print('\n',emparray)

[0. 0. 0.] 
 [[0. 0. 0.]
 [0. 0. 0.]]

 [1. 1. 1. 1.] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[0.71558562 0.48814272]
 [0.54206026 0.53828945]
 [0.13751671 0.69186681]]

 [[0.71558562 0.48814272 0.54206026]
 [0.53828945 0.13751671 0.69186681]]


In [30]:
#an array with constant
arrcons = np.full((2,2),7) #fills with 7
print(arrcons)

#creating an array from 1 - 9(+1 increment)
arr = np.arange(1,10,1)
print(arr)

#array with random integers
arr1 = np.random.randint(90,100,7) #7 random integers
print(arr1)

arr2 = np.random.randn(10) #standart distribution
print(arr2)

[[7 7]
 [7 7]]
[1 2 3 4 5 6 7 8 9]
[98 91 97 99 99 97 91]
[-0.32416334 -0.33341825 -0.39051674  0.23319381  0.33799241  1.47094365
  0.80318307  2.58029895 -0.57400577  0.08331342]


In [37]:
#creating arrays from existing array:
x = [1,2,3]
a = np.asarray(x) #converting list to array
print(a)

x1 = [(4,5,6),(7,8,9)]
a1 = np.asarray(x1) #tupple to array
print(a1)
print(a1.shape) #dimension


[1 2 3]
[[4 5 6]
 [7 8 9]]
(2, 3)


In [44]:
#array resizing
a = np.array([[4,5,6],[7,8,9]])
a.shape = (3,2)
print(a)

b = a.reshape(2,3) #reshape method
print(b)
print(b.ndim)
print(b.size)
print(b.dtype.name)
print(type(b))

[[4 5]
 [6 7]
 [8 9]]
[[4 5 6]
 [7 8 9]]
2
6
int64
<class 'numpy.ndarray'>
